### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by 2mac** [Kingdaro/minejumper#1]
Please license this work so that contributors and distributors know their rights and how they can license their own changes.

**Comment by Kingdaro** [comment]
It's about time that I resolve this issue, even though it may not be as relevant now. The discrepancy here is that I'd obtained the background image from an open source game art website, and I seem to have lost the source for it, so for the time being, I'll put this project under creative commons, and I'll change it later if a discrepancy comes up involving this image or anything else involved in the project. Thanks for letting me know.

**Comment by Kingdaro** [comment]
I've chosen MIT, because I don't really care what's done with it at this point. Do as you please.
